---
sudo: required
dist: bionic
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:
    

    - name: "create your own Linux Distribution with Yocto  on amd64 xenial"
      dist: xenial
      arch: amd64
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-yocto-xenial
      after_success:
        - deactivate
